/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as MiaMilleryRouteImport } from './routes/mia-millery'
import { Route as FisioterapeutaRouteImport } from './routes/fisioterapeuta'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'

const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const MiaMilleryRoute = MiaMilleryRouteImport.update({
  id: '/mia-millery',
  path: '/mia-millery',
  getParentRoute: () => rootRouteImport,
} as any)
const FisioterapeutaRoute = FisioterapeutaRouteImport.update({
  id: '/fisioterapeuta',
  path: '/fisioterapeuta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/fisioterapeuta': typeof FisioterapeutaRoute
  '/mia-millery': typeof MiaMilleryRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/fisioterapeuta': typeof FisioterapeutaRoute
  '/mia-millery': typeof MiaMilleryRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/contacto': typeof ContactoRoute
  '/fisioterapeuta': typeof FisioterapeutaRoute
  '/mia-millery': typeof MiaMilleryRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/fisioterapeuta'
    | '/mia-millery'
    | '/politica-de-cookies'
    | '/politica-de-privacidad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/fisioterapeuta'
    | '/mia-millery'
    | '/politica-de-cookies'
    | '/politica-de-privacidad'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/contacto'
    | '/fisioterapeuta'
    | '/mia-millery'
    | '/politica-de-cookies'
    | '/politica-de-privacidad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  ContactoRoute: typeof ContactoRoute
  FisioterapeutaRoute: typeof FisioterapeutaRoute
  MiaMilleryRoute: typeof MiaMilleryRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mia-millery': {
      id: '/mia-millery'
      path: '/mia-millery'
      fullPath: '/mia-millery'
      preLoaderRoute: typeof MiaMilleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fisioterapeuta': {
      id: '/fisioterapeuta'
      path: '/fisioterapeuta'
      fullPath: '/fisioterapeuta'
      preLoaderRoute: typeof FisioterapeutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  ContactoRoute: ContactoRoute,
  FisioterapeutaRoute: FisioterapeutaRoute,
  MiaMilleryRoute: MiaMilleryRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
