/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MiaMilleryRouteImport } from './routes/mia-millery'
import { Route as FisioterapeutaRouteImport } from './routes/fisioterapeuta'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const MiaMilleryRoute = MiaMilleryRouteImport.update({
  id: '/mia-millery',
  path: '/mia-millery',
  getParentRoute: () => rootRouteImport,
} as any)
const FisioterapeutaRoute = FisioterapeutaRouteImport.update({
  id: '/fisioterapeuta',
  path: '/fisioterapeuta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/fisioterapeuta': typeof FisioterapeutaRoute
  '/mia-millery': typeof MiaMilleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/fisioterapeuta': typeof FisioterapeutaRoute
  '/mia-millery': typeof MiaMilleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/fisioterapeuta': typeof FisioterapeutaRoute
  '/mia-millery': typeof MiaMilleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacto' | '/fisioterapeuta' | '/mia-millery'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/fisioterapeuta' | '/mia-millery'
  id: '__root__' | '/' | '/contacto' | '/fisioterapeuta' | '/mia-millery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  FisioterapeutaRoute: typeof FisioterapeutaRoute
  MiaMilleryRoute: typeof MiaMilleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mia-millery': {
      id: '/mia-millery'
      path: '/mia-millery'
      fullPath: '/mia-millery'
      preLoaderRoute: typeof MiaMilleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fisioterapeuta': {
      id: '/fisioterapeuta'
      path: '/fisioterapeuta'
      fullPath: '/fisioterapeuta'
      preLoaderRoute: typeof FisioterapeutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  FisioterapeutaRoute: FisioterapeutaRoute,
  MiaMilleryRoute: MiaMilleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
